# This file was generated by GoReleaser. DO NOT EDIT.
cask "qrshare" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "cc1b4090e8d1ab210af0d498902ef09d8a72e259dba41311969d4b99f933e7b2"
      url "https://github.com/edaywalid/qrshare/releases/download/v#{version}/qrshare_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "980be16567b0f4af1ad43e89a1b9c8be24e0fb1d8edf06dfb198bb6e5a226dd8"
      url "https://github.com/edaywalid/qrshare/releases/download/v#{version}/qrshare_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "53547d7d3f038fa81420f70049725efc8f5e2cb29fdd274f3327f1bb4550e2bc"
      url "https://github.com/edaywalid/qrshare/releases/download/v#{version}/qrshare_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cfbb06bb1ee0c93dea9f46c3476bdb33c7471e8e0279694f865e7c4a32e81ea6"
      url "https://github.com/edaywalid/qrshare/releases/download/v#{version}/qrshare_#{version}_linux_arm64.tar.gz"
    end
  end

  name "qrshare"
  desc "Share files, folders, text, or a URL to your phone over wifi, no app or cloud"
  homepage "https://github.com/edaywalid/qrshare"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qrshare"
  bash_completion "completions/qrshare.bash"
  fish_completion "completions/qrshare.fish"
  zsh_completion "completions/qrshare.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qrshare"]
    end
  end

  # No zap stanza required

end
