# This file was generated by GoReleaser. DO NOT EDIT.
cask "qrshare" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "f57e6238d77f9016e83226ff2eb6c31f859d44b9b7450d5df8a2ad76f8077510"
      url "https://github.com/edaywalid/qrshare/releases/download/v#{version}/qrshare_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4752fbb703c234cf66c7af270bc80b4076d99e8c1c0c0b7ca2599e8a0285df6e"
      url "https://github.com/edaywalid/qrshare/releases/download/v#{version}/qrshare_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ca8f9b4aa6c6f3aadc770d7db1672ddf2f3993df82c4f7089cc50699ddbeaded"
      url "https://github.com/edaywalid/qrshare/releases/download/v#{version}/qrshare_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2ff43f4d78d51432ef5963d17202212011064aa604392d97d6e38b3be26a4da5"
      url "https://github.com/edaywalid/qrshare/releases/download/v#{version}/qrshare_#{version}_linux_arm64.tar.gz"
    end
  end

  name "qrshare"
  desc "Share files, folders, text, or a URL to your phone over wifi, no app or cloud"
  homepage "https://github.com/edaywalid/qrshare"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qrshare"
  bash_completion "completions/qrshare.bash"
  fish_completion "completions/qrshare.fish"
  zsh_completion "completions/qrshare.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qrshare"]
    end
  end

  # No zap stanza required

end
