# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Undo < Formula
  desc "Undo what the last shell command did to the filesystem"
  homepage "https://github.com/edaywalid/undo"
  version "0.3.0"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/edaywalid/undo/releases/download/v0.3.0/undo_0.3.0_linux_amd64.tar.gz"
    sha256 "78e19c58a75241880eff38832dd3f0a63c346d10e6e7a9fdf4f82cdca585476d"
    define_method(:install) do
      bin.install "undo"
      arch = Hardware::CPU.arm? ? "arm64" : "amd64"
      (lib/"undo").install "build/libundo_#{arch}.so" => "libundo.so"
      (share/"undo").install Dir["shell/*"]
      zsh_completion.install "completions/_undo"
      bash_completion.install "completions/undo.bash" => "undo"
      fish_completion.install "completions/undo.fish"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/edaywalid/undo/releases/download/v0.3.0/undo_0.3.0_linux_arm64.tar.gz"
    sha256 "902f345c86d38d3ec63d0b84fbb7ff191ddbcecdec08b48e4bcf0c14b197c62b"
    define_method(:install) do
      bin.install "undo"
      arch = Hardware::CPU.arm? ? "arm64" : "amd64"
      (lib/"undo").install "build/libundo_#{arch}.so" => "libundo.so"
      (share/"undo").install Dir["shell/*"]
      zsh_completion.install "completions/_undo"
      bash_completion.install "completions/undo.bash" => "undo"
      fish_completion.install "completions/undo.fish"
    end
  end

  def caveats
    <<~EOS
      Add the hook for your shell:
        zsh:   source #{HOMEBREW_PREFIX}/share/undo/undo.zsh
        bash:  source #{HOMEBREW_PREFIX}/share/undo/undo.bash
        fish:  source #{HOMEBREW_PREFIX}/share/undo/undo.fish
    EOS
  end

  test do
    system "#{bin}/undo", "--version"
  end
end
