# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Undo < Formula
  desc "Undo what the last shell command did to the filesystem"
  homepage "https://github.com/edaywalid/undo"
  version "0.2.7"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/edaywalid/undo/releases/download/v0.2.7/undo_0.2.7_linux_amd64.tar.gz"
    sha256 "ecf48dcb5aa070393b45575dcf014bd394d08a03aaa61e13be493dc2bca669d9"
    define_method(:install) do
      bin.install "undo"
      arch = Hardware::CPU.arm? ? "arm64" : "amd64"
      (lib/"undo").install "build/libundo_#{arch}.so" => "libundo.so"
      (share/"undo").install Dir["shell/*"]
      zsh_completion.install "completions/_undo"
      bash_completion.install "completions/undo.bash" => "undo"
      fish_completion.install "completions/undo.fish"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/edaywalid/undo/releases/download/v0.2.7/undo_0.2.7_linux_arm64.tar.gz"
    sha256 "48cc5fa4f54c5b7f82ee7ef87b8c3da8355f1f15b2cf4973cd04cb2c1505f6d5"
    define_method(:install) do
      bin.install "undo"
      arch = Hardware::CPU.arm? ? "arm64" : "amd64"
      (lib/"undo").install "build/libundo_#{arch}.so" => "libundo.so"
      (share/"undo").install Dir["shell/*"]
      zsh_completion.install "completions/_undo"
      bash_completion.install "completions/undo.bash" => "undo"
      fish_completion.install "completions/undo.fish"
    end
  end

  def caveats
    <<~EOS
      Add the hook for your shell:
        zsh:   source #{HOMEBREW_PREFIX}/share/undo/undo.zsh
        bash:  source #{HOMEBREW_PREFIX}/share/undo/undo.bash
        fish:  source #{HOMEBREW_PREFIX}/share/undo/undo.fish
    EOS
  end

  test do
    system "#{bin}/undo", "--version"
  end
end
