# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Undo < Formula
  desc "Undo what the last shell command did to the filesystem"
  homepage "https://github.com/edaywalid/undo"
  version "0.2.1"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/edaywalid/undo/releases/download/v0.2.1/undo_0.2.1_linux_amd64.tar.gz"
    sha256 "050c8624ecf9198c1ff34f2bd6c4119d7ee8c9cec466b330538817533474c04f"
    define_method(:install) do
      bin.install "undo"
      arch = Hardware::CPU.arm? ? "arm64" : "amd64"
      (lib/"undo").install "build/libundo_#{arch}.so" => "libundo.so"
      (share/"undo").install Dir["shell/*"]
      zsh_completion.install "completions/_undo"
      bash_completion.install "completions/undo.bash" => "undo"
      fish_completion.install "completions/undo.fish"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/edaywalid/undo/releases/download/v0.2.1/undo_0.2.1_linux_arm64.tar.gz"
    sha256 "213a82985d3c90e21482dcae666f479750e6935fde0885c7c0f1988f57694002"
    define_method(:install) do
      bin.install "undo"
      arch = Hardware::CPU.arm? ? "arm64" : "amd64"
      (lib/"undo").install "build/libundo_#{arch}.so" => "libundo.so"
      (share/"undo").install Dir["shell/*"]
      zsh_completion.install "completions/_undo"
      bash_completion.install "completions/undo.bash" => "undo"
      fish_completion.install "completions/undo.fish"
    end
  end

  def caveats
    <<~EOS
      Add the hook for your shell:
        zsh:   source #{HOMEBREW_PREFIX}/share/undo/undo.zsh
        bash:  source #{HOMEBREW_PREFIX}/share/undo/undo.bash
        fish:  source #{HOMEBREW_PREFIX}/share/undo/undo.fish
    EOS
  end

  test do
    system "#{bin}/undo", "--version"
  end
end
